export const departments = [
	{
		code_dpt: '01',
		dpt_name: 'Ain',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Bourg-en-Bresse',
	},
	{
		code_dpt: '02',
		dpt_name: 'Aisne',
		region_name: 'Hauts-de-France',
		pref_name: 'Laon',
	},
	{
		code_dpt: '03',
		dpt_name: 'Allier',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Moulins',
	},
	{
		code_dpt: '04',
		dpt_name: 'Alpes-de-Haute-Provence',
		region_name: "Provence-Alpes-Côte d'Azur",
		pref_name: 'Digne-les-Bains',
	},
	{
		code_dpt: '05',
		dpt_name: 'Hautes-Alpes',
		region_name: "Provence-Alpes-Côte d'Azur",
		pref_name: 'Gap',
	},
	{
		code_dpt: '06',
		dpt_name: 'Alpes-Maritimes',
		region_name: "Provence-Alpes-Côte d'Azur",
		pref_name: 'Nice',
	},
	{
		code_dpt: '07',
		dpt_name: 'Ardèche',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Privas',
	},
	{
		code_dpt: '08',
		dpt_name: 'Ardennes',
		region_name: 'Grand Est',
		pref_name: 'Charleville-Mézières',
	},
	{
		code_dpt: '09',
		dpt_name: 'Ariège',
		region_name: 'Occitanie',
		pref_name: 'Foix',
	},
	{
		code_dpt: '10',
		dpt_name: 'Aube',
		region_name: 'Grand Est',
		pref_name: 'Troyes',
	},
	{
		code_dpt: '11',
		dpt_name: 'Aude',
		region_name: 'Occitanie',
		pref_name: 'Carcassonne',
	},
	{
		code_dpt: '12',
		dpt_name: 'Aveyron',
		region_name: 'Occitanie',
		pref_name: 'Rodez',
	},
	{
		code_dpt: '13',
		dpt_name: 'Bouches-du-Rhône',
		region_name: "Provence-Alpes-Côte d'Azur",
		pref_name: 'Marseille',
	},
	{
		code_dpt: '14',
		dpt_name: 'Calvados',
		region_name: 'Normandie',
		pref_name: 'Caen',
	},
	{
		code_dpt: '15',
		dpt_name: 'Cantal',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Aurillac',
	},
	{
		code_dpt: '16',
		dpt_name: 'Charente',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Angoulême',
	},
	{
		code_dpt: '17',
		dpt_name: 'Charente-Maritime',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'La Rochelle',
	},
	{
		code_dpt: '18',
		dpt_name: 'Cher',
		region_name: 'Centre-Val de Loire',
		pref_name: 'Bourges',
	},
	{
		code_dpt: '19',
		dpt_name: 'Corrèze',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Tulle',
	},
	{
		code_dpt: '2A',
		dpt_name: 'Corse-du-Sud',
		region_name: 'Corse',
		pref_name: 'Ajaccio',
	},
	{
		code_dpt: '2B',
		dpt_name: 'Haute-Corse',
		region_name: 'Corse',
		pref_name: 'Bastia',
	},
	{
		code_dpt: '21',
		dpt_name: "Côte-d'Or",
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Dijon',
	},
	{
		code_dpt: '22',
		dpt_name: "Côtes-d'Armor",
		region_name: 'Bretagne',
		pref_name: 'Saint-Brieuc',
	},
	{
		code_dpt: '23',
		dpt_name: 'Creuse',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Guéret',
	},
	{
		code_dpt: '24',
		dpt_name: 'Dordogne',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Périgueux',
	},
	{
		code_dpt: '25',
		dpt_name: 'Doubs',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Besançon',
	},
	{
		code_dpt: '26',
		dpt_name: 'Drôme',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Valence',
	},
	{
		code_dpt: '27',
		dpt_name: 'Eure',
		region_name: 'Normandie',
		pref_name: 'Évreux',
	},
	{
		code_dpt: '28',
		dpt_name: 'Eure-et-Loir',
		region_name: 'Centre-Val de Loire',
		pref_name: 'Chartres',
	},
	{
		code_dpt: '29',
		dpt_name: 'Finistère',
		region_name: 'Bretagne',
		pref_name: 'Quimper',
	},
	{
		code_dpt: '30',
		dpt_name: 'Gard',
		region_name: 'Occitanie',
		pref_name: 'Nîmes',
	},
	{
		code_dpt: '31',
		dpt_name: 'Haute-Garonne',
		region_name: 'Occitanie',
		pref_name: 'Toulouse',
	},
	{
		code_dpt: '32',
		dpt_name: 'Gers',
		region_name: 'Occitanie',
		pref_name: 'Auch',
	},
	{
		code_dpt: '33',
		dpt_name: 'Gironde',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Bordeaux',
	},
	{
		code_dpt: '34',
		dpt_name: 'Hérault',
		region_name: 'Occitanie',
		pref_name: 'Montpellier',
	},
	{
		code_dpt: '35',
		dpt_name: 'Ille-et-Vilaine',
		region_name: 'Bretagne',
		pref_name: 'Rennes',
	},
	{
		code_dpt: '36',
		dpt_name: 'Indre',
		region_name: 'Centre-Val de Loire',
		pref_name: 'Châteauroux',
	},
	{
		code_dpt: '37',
		dpt_name: 'Indre-et-Loire',
		region_name: 'Centre-Val de Loire',
		pref_name: 'Tours',
	},
	{
		code_dpt: '38',
		dpt_name: 'Isère',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Grenoble',
	},
	{
		code_dpt: '39',
		dpt_name: 'Jura',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Lons-le-Saunier',
	},
	{
		code_dpt: '40',
		dpt_name: 'Landes',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Mont-de-Marsan',
	},
	{
		code_dpt: '41',
		dpt_name: 'Loir-et-Cher',
		region_name: 'Centre-Val de Loire',
		pref_name: 'Blois',
	},
	{
		code_dpt: '42',
		dpt_name: 'Loire',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Saint-Étienne',
	},
	{
		code_dpt: '43',
		dpt_name: 'Haute-Loire',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Le Puy-en-Velay',
	},
	{
		code_dpt: '44',
		dpt_name: 'Loire-Atlantique',
		region_name: 'Pays de la Loire',
		pref_name: 'Nantes',
	},
	{
		code_dpt: '45',
		dpt_name: 'Loiret',
		region_name: 'Centre-Val de Loire',
		pref_name: 'Orléans',
	},
	{
		code_dpt: '46',
		dpt_name: 'Lot',
		region_name: 'Occitanie',
		pref_name: 'Cahors',
	},
	{
		code_dpt: '47',
		dpt_name: 'Lot-et-Garonne',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Agen',
	},
	{
		code_dpt: '48',
		dpt_name: 'Lozère',
		region_name: 'Occitanie',
		pref_name: 'Mende',
	},
	{
		code_dpt: '49',
		dpt_name: 'Maine-et-Loire',
		region_name: 'Pays de la Loire',
		pref_name: 'Angers',
	},
	{
		code_dpt: '50',
		dpt_name: 'Manche',
		region_name: 'Normandie',
		pref_name: 'Saint-Lô',
	},
	{
		code_dpt: '51',
		dpt_name: 'Marne',
		region_name: 'Grand Est',
		pref_name: 'Châlons-en-Champagne',
	},
	{
		code_dpt: '52',
		dpt_name: 'Haute-Marne',
		region_name: 'Grand Est',
		pref_name: 'Chaumont',
	},
	{
		code_dpt: '53',
		dpt_name: 'Mayenne',
		region_name: 'Pays de la Loire',
		pref_name: 'Laval',
	},
	{
		code_dpt: '54',
		dpt_name: 'Meurthe-et-Moselle',
		region_name: 'Grand Est',
		pref_name: 'Nancy',
	},
	{
		code_dpt: '55',
		dpt_name: 'Meuse',
		region_name: 'Grand Est',
		pref_name: 'Bar-le-Duc',
	},
	{
		code_dpt: '56',
		dpt_name: 'Morbihan',
		region_name: 'Bretagne',
		pref_name: 'Vannes',
	},
	{
		code_dpt: '57',
		dpt_name: 'Moselle',
		region_name: 'Grand Est',
		pref_name: 'Metz',
	},
	{
		code_dpt: '58',
		dpt_name: 'Nièvre',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Nevers',
	},
	{
		code_dpt: '59',
		dpt_name: 'Nord',
		region_name: 'Hauts-de-France',
		pref_name: 'Lille',
	},
	{
		code_dpt: '60',
		dpt_name: 'Oise',
		region_name: 'Hauts-de-France',
		pref_name: 'Beauvais',
	},
	{
		code_dpt: '61',
		dpt_name: 'Orne',
		region_name: 'Normandie',
		pref_name: 'Alençon',
	},
	{
		code_dpt: '62',
		dpt_name: 'Pas-de-Calais',
		region_name: 'Hauts-de-France',
		pref_name: 'Arras',
	},
	{
		code_dpt: '63',
		dpt_name: 'Puy-de-Dôme',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Clermont-Ferrand',
	},
	{
		code_dpt: '64',
		dpt_name: 'Pyrénées-Atlantiques',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Pau',
	},
	{
		code_dpt: '65',
		dpt_name: 'Hautes-Pyrénées',
		region_name: 'Occitanie',
		pref_name: 'Tarbes',
	},
	{
		code_dpt: '66',
		dpt_name: 'Pyrénées-Orientales',
		region_name: 'Occitanie',
		pref_name: 'Perpignan',
	},
	{
		code_dpt: '67',
		dpt_name: 'Bas-Rhin',
		region_name: 'Grand Est',
		pref_name: 'Strasbourg',
	},
	{
		code_dpt: '68',
		dpt_name: 'Haut-Rhin',
		region_name: 'Grand Est',
		pref_name: 'Colmar',
	},
	{
		code_dpt: '69',
		dpt_name: 'Rhône',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Lyon',
	},
	{
		code_dpt: '70',
		dpt_name: 'Haute-Saône',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Vesoul',
	},
	{
		code_dpt: '71',
		dpt_name: 'Saône-et-Loire',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Macon',
	},
	{
		code_dpt: '72',
		dpt_name: 'Sarthe',
		region_name: 'Pays de la Loire',
		pref_name: 'Le Mans',
	},
	{
		code_dpt: '73',
		dpt_name: 'Savoie',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Chambéry',
	},
	{
		code_dpt: '74',
		dpt_name: 'Haute-Savoie',
		region_name: 'Auvergne-Rhône-Alpes',
		pref_name: 'Annecy',
	},
	{
		code_dpt: '75',
		dpt_name: 'Paris',
		region_name: 'Île-de-France',
		pref_name: 'Paris',
	},
	{
		code_dpt: '76',
		dpt_name: 'Seine-Maritime',
		region_name: 'Normandie',
		pref_name: 'Rouen',
	},
	{
		code_dpt: '77',
		dpt_name: 'Seine-et-Marne',
		region_name: 'Île-de-France',
		pref_name: 'Melun',
	},
	{
		code_dpt: '78',
		dpt_name: 'Yvelines',
		region_name: 'Île-de-France',
		pref_name: 'Versailles',
	},
	{
		code_dpt: '79',
		dpt_name: 'Deux-Sèvres',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Niort',
	},
	{
		code_dpt: '80',
		dpt_name: 'Somme',
		region_name: 'Hauts-de-France',
		pref_name: 'Amiens',
	},
	{
		code_dpt: '81',
		dpt_name: 'Tarn',
		region_name: 'Occitanie',
		pref_name: 'Albi',
	},
	{
		code_dpt: '82',
		dpt_name: 'Tarn-et-Garonne',
		region_name: 'Occitanie',
		pref_name: 'Montauban',
	},
	{
		code_dpt: '83',
		dpt_name: 'Var',
		region_name: "Provence-Alpes-Côte d'Azur",
		pref_name: 'Toulon',
	},
	{
		code_dpt: '84',
		dpt_name: 'Vaucluse',
		region_name: "Provence-Alpes-Côte d'Azur",
		pref_name: 'Avignon',
	},
	{
		code_dpt: '85',
		dpt_name: 'Vendée',
		region_name: 'Pays de la Loire',
		pref_name: 'La Roche-sur-Yon',
	},
	{
		code_dpt: '86',
		dpt_name: 'Vienne',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Poitiers',
	},
	{
		code_dpt: '87',
		dpt_name: 'Haute-Vienne',
		region_name: 'Nouvelle-Aquitaine',
		pref_name: 'Limoges',
	},
	{
		code_dpt: '88',
		dpt_name: 'Vosges',
		region_name: 'Grand Est',
		pref_name: 'Épinal',
	},
	{
		code_dpt: '89',
		dpt_name: 'Yonne',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Auxerre',
	},
	{
		code_dpt: '90',
		dpt_name: 'Territoire de Belfort',
		region_name: 'Bourgogne-Franche-Comté',
		pref_name: 'Belfort',
	},
	{
		code_dpt: '91',
		dpt_name: 'Essonne',
		region_name: 'Île-de-France',
		pref_name: 'Évry',
	},
	{
		code_dpt: '92',
		dpt_name: 'Hauts-de-Seine',
		region_name: 'Île-de-France',
		pref_name: 'Nanterre',
	},
	{
		code_dpt: '93',
		dpt_name: 'Seine-Saint-Denis',
		region_name: 'Île-de-France',
		pref_name: 'Bobigny',
	},
	{
		code_dpt: '94',
		dpt_name: 'Val-de-Marne',
		region_name: 'Île-de-France',
		pref_name: 'Créteil',
	},
	{
		code_dpt: '95',
		dpt_name: "Val-d'Oise",
		region_name: 'Île-de-France',
		pref_name: 'Pontoise',
	},
	{
		code_dpt: '971',
		dpt_name: 'Guadeloupe',
		region_name: 'Guadeloupe',
		pref_name: 'Basse-Terre',
	},
	{
		code_dpt: '972',
		dpt_name: 'Martinique',
		region_name: 'Martinique',
		pref_name: 'Fort-de-France',
	},
	{
		code_dpt: '973',
		dpt_name: 'Guyane',
		region_name: 'Guyane',
		pref_name: 'Cayenne',
	},
	{
		code_dpt: '974',
		dpt_name: 'La Réunion',
		region_name: 'La Réunion',
		pref_name: 'Saint-Denis',
	},
	{
		code_dpt: '976',
		dpt_name: 'Mayotte',
		region_name: 'Mayotte',
		pref_name: 'Mamoudzou',
	},
]

export const regions = {
	TOUT: { dpt: [], color: '' },
	'Auvergne-Rhône-Alpes': {
		dpt: [
			'01',
			'03',
			'07',
			'15',
			'26',
			'38',
			'42',
			'43',
			'63',
			'69',
			'73',
			'74',
		],
		color: '#75b1e2',
	},
	'Bourgogne-Franche-Comté': {
		dpt: ['21', '25', '39', '58', '70', '71', '89', '90'],
		color: '#8bc667',
	},
	Bretagne: { dpt: ['22', '29', '35', '56'], color: '#44b7d2' },
	'Centre-Val de Loire': {
		dpt: ['18', '28', '36', '37', '41', '45'],
		color: '#cdb348',
	},
	// "Corse": {dpt: ["2A", "2B"], color: "#86c9a0"},
	Corse: { dpt: ['20'], color: '#86c9a0' },
	'Grand Est': {
		dpt: ['08', '10', '51', '52', '54', '55', '57', '67', '68', '88'],
		color: '#f2c521',
	},
	'Hauts-de-France': { dpt: ['02', '59', '60', '62', '80'], color: '#BCBCBC' },
	'Île-de-France': {
		dpt: ['75', '77', '78', '91', '92', '93', '94', '95'],
		color: '#59c1ee',
	},
	Normandie: { dpt: ['14', '27', '50', '61', '76'], color: '#f2b59a' },
	'Nouvelle-Aquitaine': {
		dpt: [
			'16',
			'17',
			'19',
			'23',
			'24',
			'33',
			'40',
			'47',
			'64',
			'79',
			'86',
			'87',
		],
		color: '#bdd76d',
	},
	Occitanie: {
		dpt: [
			'09',
			'11',
			'12',
			'30',
			'31',
			'32',
			'34',
			'46',
			'48',
			'65',
			'66',
			'81',
			'82',
		],
		color: '#f47a3c',
	},
	'Pays de la Loire': { dpt: ['44', '49', '53', '72', '85'], color: '#e398c1' },
	"Provence-Alpes-Côte d'Azur": {
		dpt: ['04', '05', '06', '13', '83', '84'],
		color: '#f09c07',
	},
	Outremer: { dpt: ['971', '972', '973', '974', '976'], color: '#BB529E' },
	// "Guadeloupe": {dpt: ["971"], color: "#FAA619"},
	// "Martinique": {dpt: ["972"], color: "#FEC641"},
	// "Guyane": {dpt: ["973"], color: "#BB529E"},
	// "La Réunion": {dpt: ["974"], color: "#B71F2A"},
	// "Mayotte": {dpt: ["976"], color: "#9F2064"},
}

export function getDptCodeFromZipcode(zipcode) {
	if (zipcode.length > 2 && zipcode.slice(0, 2) === '97') {
		return zipcode.slice(0, 3)
	}
	return zipcode.slice(0, 2)
}

export function getRegionByDpt(dptCode) {
	return Object.keys(regions).filter(r => regions[r].dpt.includes(dptCode))
}

export function getColorByDpt(dptCode) {
	// console.log(`geographic.getColorByDpt(${dptCode})`)
	const found_region = getRegionByDpt(dptCode)
	return found_region.length > 0 ? regions[found_region].color : 'white'
}

export function getDptByCode(dptCode) {
	// console.log(`geographic.getDptByCode(${dptCode})`)
	const found_dpt = departments.filter(d => d.code_dpt === dptCode)
	if (found_dpt.length === 0) return 'N/A'
	return found_dpt[0].dpt_name
}
