const myList = [
	{
		UserOfferers: [
			{
				id: 'A4',
				modelName: 'UserOfferer',
				offererId: 'YY',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-07-10T17:23:45.345978Z',
					departementCode: '93',
					email: 'nicolas.lorach@gmail.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Hautlescours',
				},
				userId: 'AGSA',
				validationToken: null,
			},
		],
		address: '2 Boulevard Anatole France 93200 Saint-Denis',
		bic: null,
		city: 'SAINT DENIS',
		dateCreated: '2018-07-11T14:31:52.157960Z',
		dateModifiedAtLastProvider: '2018-07-11T14:31:52.157941Z',
		iban: null,
		id: 'YY',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'SAINT DENIS UNION SPORT',
		postalCode: '93200',
		siren: '753364173',
		thumbCount: 0,
		validationToken: '4QUQcR7W7ks4xaD8js_nUDzwAdk',
	},
	{
		UserOfferers: [
			{
				id: '9Q',
				modelName: 'UserOfferer',
				offererId: 'AFBA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-08-01T10:01:25.213096Z',
					departementCode: '29',
					email: 'yann-peron@hotmail.fr',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Bagad Karaez',
				},
				userId: 'A9GQ',
				validationToken: null,
			},
		],
		address: 'BELLEVUE',
		bic: null,
		city: 'CARHAIX PLOUGUER',
		dateCreated: '2018-08-01T10:01:25.214050Z',
		dateModifiedAtLastProvider: '2018-08-01T10:01:25.214045Z',
		iban: null,
		id: 'AFBA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'BAGAD KARAEZ',
		postalCode: '29270',
		siren: '495407785',
		thumbCount: 0,
		validationToken: '-yRuvESOiD6rKiUgrTvoBXAUqWo',
	},
	{
		UserOfferers: [
			{
				id: 'JY',
				modelName: 'UserOfferer',
				offererId: 'AFGA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-08-03T12:07:38.020779Z',
					departementCode: '93',
					email: 'impressionslib@canalbd.net',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Librairie Impressions',
				},
				userId: 'A9PA',
				validationToken: null,
			},
		],
		address: '10 RUE JEAN MONNET',
		bic: null,
		city: 'ENGHIEN LES BAINS',
		dateCreated: '2018-08-03T12:07:38.022340Z',
		dateModifiedAtLastProvider: '2018-08-03T12:07:38.022334Z',
		iban: null,
		id: 'AFGA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LIBRAIRIE IMPRESSIONS',
		postalCode: '95880',
		siren: '333086304',
		thumbCount: 0,
		validationToken: '2RHQ0OlqdglihrG8KQKiXVPFE_E',
	},
	{
		UserOfferers: [
			{
				id: 'RU',
				modelName: 'UserOfferer',
				offererId: 'AGDA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-08-31T10:25:28.473384Z',
					departementCode: '93',
					email: 'nicolaenji@yahoo.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Nico',
				},
				userId: 'AKPA',
				validationToken: null,
			},
		],
		address: '38 RUE DES JEUNEURS',
		bic: null,
		city: 'PARIS 2',
		dateCreated: '2018-08-31T10:25:28.468290Z',
		dateModifiedAtLastProvider: '2018-08-31T10:25:28.468277Z',
		iban: null,
		id: 'AGDA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'STARBUCKS COFFEE FRANCE',
		postalCode: '75002',
		siren: '445330103',
		thumbCount: 0,
		validationToken: 'c1QsMJqpIvxn0U6HLli8m_E2Umw',
	},
	{
		UserOfferers: [
			{
				id: 'SY',
				modelName: 'UserOfferer',
				offererId: 'AGHQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-03T08:49:18.509377Z',
					departementCode: '67',
					email: 'lmener@tjp-strasbourg.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Laurence M\u00e9ner',
				},
				userId: 'AKYA',
				validationToken: null,
			},
			{
				id: '6Y',
				modelName: 'UserOfferer',
				offererId: 'AGHQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-11T15:16:37.897551Z',
					departementCode: '67',
					email: 'fmaire@tjp-strasbourg.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'TJPresponsablebilletterie',
				},
				userId: 'AMPQ',
				validationToken: null,
			},
			{
				id: 'AG2Q',
				modelName: 'UserOfferer',
				offererId: 'AGHQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-03T13:50:13.420875Z',
					departementCode: '67',
					email: 'csilva@tjp-strasbourg.com',
					firstName: 'Catherine',
					isAdmin: false,
					lastName: 'Silva',
					phoneNumber: null,
					postalCode: '67000',
					publicName: 'CDN TJP',
				},
				userId: 'APPA',
				validationToken: 'z6_PcZHuBRWnBDKhXemTVytWkXc',
			},
			{
				id: 'AHBA',
				modelName: 'UserOfferer',
				offererId: 'AGHQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-04T14:51:40.663318Z',
					departementCode: '67',
					email: 'dverger@tjp-strasbourg.com',
					firstName: 'delphine',
					isAdmin: false,
					lastName: 'verger',
					phoneNumber: null,
					postalCode: '67000',
					publicName: 'delph',
				},
				userId: 'APVQ',
				validationToken: null,
			},
		],
		address: '1 RUE DU PONT SAINT MARTIN',
		bic: null,
		city: 'STRASBOURG',
		dateCreated: '2018-09-03T08:49:18.507022Z',
		dateModifiedAtLastProvider: '2018-09-03T08:49:18.507015Z',
		iban: null,
		id: 'AGHQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'TJP',
		postalCode: '67000',
		siren: '778870964',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'UE',
				modelName: 'UserOfferer',
				offererId: 'AGMQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-04T09:37:39.068145Z',
					departementCode: '13',
					email: 'geraldine@aixqui.fr',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: "Association Aix'Qui?",
				},
				userId: 'ALAA',
				validationToken: null,
			},
		],
		address: 'CHEMIN DU COTON ROUGE',
		bic: null,
		city: 'AIX EN PROVENCE',
		dateCreated: '2018-09-04T09:37:39.069335Z',
		dateModifiedAtLastProvider: '2018-09-04T09:37:39.069327Z',
		iban: null,
		id: 'AGMQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'AIX QUI',
		postalCode: '13100',
		siren: '403142185',
		thumbCount: 0,
		validationToken: 'QLfwCKiEbMcH7XZyhtYqE3_EXJY',
	},
	{
		UserOfferers: [
			{
				id: 'UM',
				modelName: 'UserOfferer',
				offererId: 'AG8A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-04T10:17:00.417162Z',
					departementCode: '86',
					email: 'sandygimenez13@gmail.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Sandy13700',
				},
				userId: 'ALBA',
				validationToken: null,
			},
		],
		address: '2 BOULEVARD NICEPHORE NIEPCE',
		bic: null,
		city: 'CHASSENEUIL DU POITOU',
		dateCreated: '2018-09-04T10:17:00.419686Z',
		dateModifiedAtLastProvider: '2018-09-04T10:17:00.419672Z',
		iban: null,
		id: 'AG8A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'CENTRE NAT D ENSEIGNEMENT A DISTANCE',
		postalCode: '86360',
		siren: '197529050',
		thumbCount: 0,
		validationToken: 'BU6dHJWN4gqwO_Xl0HUgJ1iBBsE',
	},
	{
		UserOfferers: [
			{
				id: 'XQ',
				modelName: 'UserOfferer',
				offererId: 'AG3A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-06T10:09:56.463243Z',
					departementCode: '33',
					email: 'celine@fede-felin.org',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'FELIN',
				},
				userId: 'ALPQ',
				validationToken: null,
			},
		],
		address: '12 PLACE DE LA VICTOIRE',
		bic: null,
		city: 'BORDEAUX',
		dateCreated: '2018-09-06T10:09:56.461877Z',
		dateModifiedAtLastProvider: '2018-09-06T10:09:56.461867Z',
		iban: null,
		id: 'AG3A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'FEDERATION NAL DES LABELS INDEPENDANTS',
		postalCode: '33000',
		siren: '539096248',
		thumbCount: 0,
		validationToken: '0B9ntXMW-PFiBwm9Gblv6VMBkoM',
	},
	{
		UserOfferers: [
			{
				id: 'Y4',
				modelName: 'UserOfferer',
				offererId: 'AHCA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-07T08:24:58.611417Z',
					departementCode: '56',
					email: 'passculture@bookhemispheres.org',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Book H\u00e9misph\u00e8res',
				},
				userId: 'ALVA',
				validationToken: null,
			},
		],
		address: '2 AVENUE DES PLAGES',
		bic: null,
		city: 'KERVIGNAC',
		dateCreated: '2018-09-07T08:27:00.998437Z',
		dateModifiedAtLastProvider: '2018-09-07T08:27:00.998431Z',
		iban: null,
		id: 'AHCA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'BOOK HEMISPHERES',
		postalCode: '56700',
		siren: '514915438',
		thumbCount: 0,
		validationToken: '4PkagPTlLzsWXRVUy0TME9--IpE',
	},
	{
		UserOfferers: [
			{
				id: '2M',
				modelName: 'UserOfferer',
				offererId: 'AH9Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-08T09:19:35.240296Z',
					departementCode: '67',
					email: 'com@strasbourgfestival.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'LesFilmsduSpectre',
				},
				userId: 'AL4Q',
				validationToken: null,
			},
			{
				id: 'AJHA',
				modelName: 'UserOfferer',
				offererId: 'AH9Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-22T15:14:21.744269Z',
					departementCode: '67',
					email: 'spectrefilm@gmail.com',
					firstName: 'Daniel',
					isAdmin: false,
					lastName: 'Cohen',
					phoneNumber: null,
					postalCode: '67000',
					publicName: 'FEFFS',
				},
				userId: 'AR5A',
				validationToken: '4adP2lkfDdtI9P8-Thybn3i-PwI',
			},
		],
		address: '9 RUE DU VIEIL HOPITAL',
		bic: null,
		city: 'STRASBOURG',
		dateCreated: '2018-09-08T09:19:35.241064Z',
		dateModifiedAtLastProvider: '2018-09-08T09:19:35.241058Z',
		iban: null,
		id: 'AH9Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ASS LES FILMS DU SPECTRE',
		postalCode: '67000',
		siren: '490548963',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: '3M',
				modelName: 'UserOfferer',
				offererId: 'AH8A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-10T08:36:47.613505Z',
					departementCode: '86',
					email: 'julie.culturel@gmail.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Julie',
				},
				userId: 'AMBQ',
				validationToken: null,
			},
		],
		address: '52 RUE DE QUINCAY',
		bic: null,
		city: 'POITIERS',
		dateCreated: '2018-09-10T08:36:47.611864Z',
		dateModifiedAtLastProvider: '2018-09-10T08:36:47.611856Z',
		iban: null,
		id: 'AH8A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ATOUT PASS',
		postalCode: '86000',
		siren: '521673566',
		thumbCount: 0,
		validationToken: 'D_scB9bWbUf1Xlw2afZkdZkxyVk',
	},
	{
		UserOfferers: [
			{
				id: '4Y',
				modelName: 'UserOfferer',
				offererId: 'AHUQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-10T16:51:21.023087Z',
					departementCode: '34',
					email: 'contact@poledancebeziers.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: "L'Atelier de Manon",
				},
				userId: 'AMHQ',
				validationToken: null,
			},
		],
		address: '280 RUE FELIX NADAR',
		bic: null,
		city: 'BEZIERS',
		dateCreated: '2018-09-10T16:51:21.024441Z',
		dateModifiedAtLastProvider: '2018-09-10T16:51:21.024433Z',
		iban: null,
		id: 'AHUQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'POLE DANCE SCHOOL',
		postalCode: '34500',
		siren: '799509724',
		thumbCount: 0,
		validationToken: 'XvlxZMsfEaGyP0zng-LM1D7v1ik',
	},
	{
		UserOfferers: [
			{
				id: 'AEBA',
				modelName: 'UserOfferer',
				offererId: 'A9JA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-12T11:20:09.870890Z',
					departementCode: '67',
					email: 'lamija.saric@yahoo.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'La Mia',
				},
				userId: 'AMWA',
				validationToken: null,
			},
			{
				id: 'A9DA',
				modelName: 'UserOfferer',
				offererId: 'A9JA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-12T09:14:23.237758Z',
					departementCode: '67',
					email: 'contact@associationballade.org',
					firstName: 'Perrette',
					isAdmin: false,
					lastName: 'Ourisson',
					phoneNumber: null,
					postalCode: '67200',
					publicName: 'Association Ballade',
				},
				userId: 'AQ2Q',
				validationToken: 'zpKfhwBF30KyxVxPwvgHdcjL47Y',
			},
		],
		address: '25 RUE JACOB',
		bic: null,
		city: 'STRASBOURG',
		dateCreated: '2018-09-12T11:20:09.873660Z',
		dateModifiedAtLastProvider: '2018-09-12T11:20:09.873637Z',
		iban: null,
		id: 'A9JA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'BALLADE',
		postalCode: '67200',
		siren: '444330534',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'AEQQ',
				modelName: 'UserOfferer',
				offererId: 'A92Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-13T19:51:06.169143Z',
					departementCode: '93',
					email: 'florent@kudakude.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Kudakude',
				},
				userId: 'ANBQ',
				validationToken: null,
			},
		],
		address: '12 RUE DE LA COSSONNERIE',
		bic: null,
		city: 'PARIS 1',
		dateCreated: '2018-09-13T19:51:06.165990Z',
		dateModifiedAtLastProvider: '2018-09-13T19:51:06.165982Z',
		iban: null,
		id: 'A92Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'KUDAKUDE',
		postalCode: '75001',
		siren: '837665058',
		thumbCount: 0,
		validationToken: '59HgvpqlsGRepaGK5SB5NRvm2XU',
	},
	{
		UserOfferers: [
			{
				id: 'AESQ',
				modelName: 'UserOfferer',
				offererId: 'A95A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-14T08:19:34.822048Z',
					departementCode: '92',
					email: 'jerome.hosselet@canal-plus.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'JHCanal+',
				},
				userId: 'ANDQ',
				validationToken: null,
			},
			{
				id: 'AFDQ',
				modelName: 'UserOfferer',
				offererId: 'A95A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-17T12:12:37.627956Z',
					departementCode: '92',
					email: 'xavier.francisco@canal-plus.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'xavier.francisco',
				},
				userId: 'ANVA',
				validationToken: null,
			},
			{
				id: 'AFEQ',
				modelName: 'UserOfferer',
				offererId: 'A95A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-17T12:42:35.547056Z',
					departementCode: '92',
					email: 'marion.arnaud@canal-plus.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'marnaud',
				},
				userId: 'ANWA',
				validationToken: 'DZsvpRvyIuRtpXO0jdlF3EzwnCc',
			},
			{
				id: 'AFFA',
				modelName: 'UserOfferer',
				offererId: 'A95A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-17T13:53:39.491614Z',
					departementCode: '92',
					email: 'anthony.alimi@canal-plus.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'anthoa',
				},
				userId: 'ANWQ',
				validationToken: null,
			},
			{
				id: 'AFUA',
				modelName: 'UserOfferer',
				offererId: 'A95A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-21T11:58:17.985948Z',
					departementCode: '92',
					email: 'vivien.prieur@canal-plus.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'vprieur',
				},
				userId: 'A8HA',
				validationToken: null,
			},
			{
				id: 'AKHA',
				modelName: 'UserOfferer',
				offererId: 'A95A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-26T13:44:56.919555Z',
					departementCode: '92',
					email: 'ludwig.lorenzo@canal-plus.com',
					firstName: 'Ludwig',
					isAdmin: false,
					lastName: 'Lorenzo',
					phoneNumber: null,
					postalCode: '92130',
					publicName: 'Ludwig',
				},
				userId: 'AS3Q',
				validationToken: null,
			},
		],
		address: '1 PLACE DU SPECTACLE',
		bic: null,
		city: 'ISSY LES MOULINEAUX',
		dateCreated: '2018-09-14T08:19:34.820526Z',
		dateModifiedAtLastProvider: '2018-09-14T08:19:34.820519Z',
		iban: null,
		id: 'A95A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'GROUPE CANAL+ SA',
		postalCode: '92130',
		siren: '420624777',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'AFPA',
				modelName: 'UserOfferer',
				offererId: 'AJYA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-20T08:15:39.559802Z',
					departementCode: '51',
					email: 'dacosta.jeremy95190@free.fr',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Scm harvey da costa ',
				},
				userId: 'A8CA',
				validationToken: null,
			},
		],
		address: '14 RUE SIMON',
		bic: null,
		city: 'REIMS',
		dateCreated: '2018-09-20T08:15:39.556629Z',
		dateModifiedAtLastProvider: '2018-09-20T08:15:39.556618Z',
		iban: null,
		id: 'AJYA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'SCM HARVEY DA COSTA',
		postalCode: '51100',
		siren: '808945091',
		thumbCount: 0,
		validationToken: 'fIEc7O-WXsdw_usSsUrSQKXfPoU',
	},
	{
		UserOfferers: [
			{
				id: 'AFRQ',
				modelName: 'UserOfferer',
				offererId: 'AJ3A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-20T14:56:35.149216Z',
					departementCode: '59',
					email: 'contact@nordshogun.fr',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Nord Shogun',
				},
				userId: 'A8EA',
				validationToken: null,
			},
		],
		address: '50 RUE JEAN JAURES',
		bic: null,
		city: 'FACHES THUMESNIL',
		dateCreated: '2018-09-20T14:56:35.150600Z',
		dateModifiedAtLastProvider: '2018-09-20T14:56:35.150593Z',
		iban: null,
		id: 'AJ3A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'NORD SHOGUN',
		postalCode: '59155',
		siren: '528216443',
		thumbCount: 0,
		validationToken: '9f3Y4FiCwlNv_o3wL_6fCjtVwLs',
	},
	{
		UserOfferers: [
			{
				id: 'AFYA',
				modelName: 'UserOfferer',
				offererId: 'AKBA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-24T11:42:30.938743Z',
					departementCode: '93',
					email: 'benoit@drgroov.com',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: "dr.groov'",
				},
				userId: 'A8LQ',
				validationToken: null,
			},
		],
		address: '21 RUE DU REPOS',
		bic: null,
		city: 'PARIS 20',
		dateCreated: '2018-09-24T11:42:30.935432Z',
		dateModifiedAtLastProvider: '2018-09-24T11:42:30.935420Z',
		iban: null,
		id: 'AKBA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'DR GROOV',
		postalCode: '75020',
		siren: '831092689',
		thumbCount: 0,
		validationToken: 'Jt--3bW42gq9bbVyMV1s-UVFi-I',
	},
	{
		UserOfferers: [
			{
				id: 'AFYQ',
				modelName: 'UserOfferer',
				offererId: 'AKCQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-24T13:00:06.907966Z',
					departementCode: '93',
					email: 'laure.de-guerny@pole-emploi.fr',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'PEJ',
				},
				userId: 'A8MA',
				validationToken: null,
			},
			{
				id: 'AGDA',
				modelName: 'UserOfferer',
				offererId: 'AKCQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-26T14:34:00.067994Z',
					departementCode: '75',
					email: 'shanicem973@gmail.com',
					firstName: 'Shanice ',
					isAdmin: false,
					lastName: 'MAGLOIRE',
					phoneNumber: null,
					postalCode: '75020',
					publicName: 'Shanice ',
				},
				userId: 'A8YQ',
				validationToken: 'uUkoFb_CzqUWbahfDOLHHpHml6Y',
			},
		],
		address: '1 AVENUE DU DOCTEUR GLEY',
		bic: null,
		city: 'PARIS 20',
		dateCreated: '2018-09-24T13:00:06.911892Z',
		dateModifiedAtLastProvider: '2018-09-24T13:00:06.911876Z',
		iban: null,
		id: 'AKCQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'POLE EMPLOI',
		postalCode: '75020',
		siren: '130005481',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'AFZQ',
				modelName: 'UserOfferer',
				offererId: 'AKEA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-24T15:31:14.691107Z',
					departementCode: '57',
					email: 'contact@jeanjacques-dumont.org',
					firstName: '',
					isAdmin: false,
					lastName: '',
					phoneNumber: null,
					postalCode: '',
					publicName: 'Jean-Jacques Dumont',
				},
				userId: 'A8NA',
				validationToken: null,
			},
		],
		address: '34 RUE PRINCIPALE',
		bic: null,
		city: 'HAMPONT',
		dateCreated: '2018-09-24T15:31:14.688426Z',
		dateModifiedAtLastProvider: '2018-09-24T15:31:14.688415Z',
		iban: null,
		id: 'AKEA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MONSIEUR JEAN DUMONT',
		postalCode: '57170',
		siren: '448873216',
		thumbCount: 0,
		validationToken: 'vlO-h5nRBzeDvZnm56YgKrsLiOE',
	},
	{
		UserOfferers: [
			{
				id: 'AGBA',
				modelName: 'UserOfferer',
				offererId: 'AKNQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-26T11:48:33.646066Z',
					departementCode: '44',
					email: 'hyperu.saintphilbertdegrandlieu.culture@systeme-u.fr',
					firstName: 'uculture',
					isAdmin: false,
					lastName: 'uculture',
					phoneNumber: null,
					postalCode: '44310',
					publicName: 'uculture',
				},
				userId: 'A8WQ',
				validationToken: null,
			},
		],
		address: 'CENTRE COMMERCIAL',
		bic: null,
		city: 'SAINT-PHILBERT-DE-GRAND-LIEU',
		dateCreated: '2018-09-26T11:48:33.644677Z',
		dateModifiedAtLastProvider: '2018-09-26T11:48:33.644671Z',
		iban: null,
		id: 'AKNQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'PHILDIS',
		postalCode: '44310',
		siren: '399548080',
		thumbCount: 0,
		validationToken: 'NpFIgA2MtxQ82Eco-WYkIzOe9CI',
	},
	{
		UserOfferers: [
			{
				id: 'AGLA',
				modelName: 'UserOfferer',
				offererId: 'AKYQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-27T20:56:41.240410Z',
					departementCode: '29',
					email: 'Laobrateatral@gmail.com',
					firstName: 'La Obra',
					isAdmin: false,
					lastName: 'Strolllad',
					phoneNumber: null,
					postalCode: '29790',
					publicName: 'la obra',
				},
				userId: 'A87Q',
				validationToken: null,
			},
			{
				id: 'AGUA',
				modelName: 'UserOfferer',
				offererId: 'AKYQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-01T12:32:21.661399Z',
					departementCode: '29',
					email: 'laobrateatral@gmail.com',
					firstName: 'La Obra',
					isAdmin: false,
					lastName: 'Strollad ',
					phoneNumber: null,
					postalCode: '29790',
					publicName: 'La Obra',
				},
				userId: 'AP9A',
				validationToken: null,
			},
		],
		address: 'RUE JEAN-LOUIS LE GOFF',
		bic: null,
		city: 'PONT CROIX',
		dateCreated: '2018-09-27T20:56:41.238873Z',
		dateModifiedAtLastProvider: '2018-09-27T20:56:41.238867Z',
		iban: null,
		id: 'AKYQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'STROLLAD LA OBRA',
		postalCode: '29790',
		siren: '478460769',
		thumbCount: 0,
		validationToken: 'MI42rkALYyGyJczEaJ40ZEaOUc8',
	},
	{
		UserOfferers: [
			{
				id: 'AGPA',
				modelName: 'UserOfferer',
				offererId: 'AK4Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-28T16:19:39.025879Z',
					departementCode: '92',
					email: 'janaa0109@gmail.com',
					firstName: 'janadan',
					isAdmin: false,
					lastName: 'ilankumaran',
					phoneNumber: null,
					postalCode: '92500',
					publicName: 'janaa',
				},
				userId: 'APDQ',
				validationToken: null,
			},
			{
				id: 'AJ4Q',
				modelName: 'UserOfferer',
				offererId: 'AK4Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T17:26:40.474325Z',
					departementCode: '92',
					email: 'anasneymar93@gmail.com',
					firstName: 'Hamiche',
					isAdmin: false,
					lastName: 'Bilal',
					phoneNumber: null,
					postalCode: '92500',
					publicName: 'Ham',
				},
				userId: 'ASRA',
				validationToken: 'd6a6-vnJ2srG91Qtx8MXKvYqySM',
			},
		],
		address: '7 RUE HENRI SAINTE CLAIRE DEVILLE',
		bic: null,
		city: 'RUEIL MALMAISON',
		dateCreated: '2018-09-28T16:19:39.027860Z',
		dateModifiedAtLastProvider: '2018-09-28T16:19:39.027852Z',
		iban: null,
		id: 'AK4Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'PEUGEOT SA',
		postalCode: '92500',
		siren: '552100554',
		thumbCount: 0,
		validationToken: 'TTQlr4FARQ6s2TfJLFAa2kvPwJM',
	},
	{
		UserOfferers: [
			{
				id: 'AGPQ',
				modelName: 'UserOfferer',
				offererId: 'AK5A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-09-28T16:51:19.661954Z',
					departementCode: '93',
					email: 'alexishelluna@outlook.ff',
					firstName: 'Alexis',
					isAdmin: false,
					lastName: 'Hel',
					phoneNumber: null,
					postalCode: '75006',
					publicName: 'ciro_hl',
				},
				userId: 'APEA',
				validationToken: null,
			},
		],
		address: '5 RUE COETLOGON',
		bic: null,
		city: 'PARIS 6',
		dateCreated: '2018-09-28T16:51:19.663137Z',
		dateModifiedAtLastProvider: '2018-09-28T16:51:19.663132Z',
		iban: null,
		id: 'AK5A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'SYND COPR DU 5 RUE COETLOGON 75006',
		postalCode: '75006',
		siren: '039138607',
		thumbCount: 0,
		validationToken: '1rG5wQQF80e_f6nqfDa6O7COgxE',
	},
	{
		UserOfferers: [
			{
				id: 'AG2A',
				modelName: 'UserOfferer',
				offererId: 'ALHA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-03T12:15:02.719117Z',
					departementCode: '93',
					email: 'romain.delassus@me.com',
					firstName: 'Romain',
					isAdmin: false,
					lastName: 'Delassus',
					phoneNumber: null,
					postalCode: '75005',
					publicName: 'Romain',
				},
				userId: 'AP8Q',
				validationToken: null,
			},
			{
				id: 'A9KQ',
				modelName: 'UserOfferer',
				offererId: 'ALHA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-12T13:44:08.680927Z',
					departementCode: '75',
					email: 'romain.del@me.com',
					firstName: 'Delassus',
					isAdmin: false,
					lastName: 'Romain',
					phoneNumber: null,
					postalCode: '75005',
					publicName: 'Romain',
				},
				userId: 'ARAQ',
				validationToken: null,
			},
			{
				id: 'A9LA',
				modelName: 'UserOfferer',
				offererId: 'ALHA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-12T13:45:41.893188Z',
					departementCode: '75',
					email: 'rom1.delassus@gmail.com',
					firstName: 'Delassus',
					isAdmin: false,
					lastName: 'Romain',
					phoneNumber: null,
					postalCode: '75005',
					publicName: 'Romain',
				},
				userId: 'ARBA',
				validationToken: null,
			},
			{
				id: 'AKVA',
				modelName: 'UserOfferer',
				offererId: 'ALHA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-31T10:51:59.032673Z',
					departementCode: '93',
					email: 'romain.delassus@mines.org',
					firstName: 'Delassus',
					isAdmin: false,
					lastName: 'Romain',
					phoneNumber: null,
					postalCode: '75005',
					publicName: 'Romain',
				},
				userId: 'ATJQ',
				validationToken: 'JFlY1rLhKUYtDOC1ECzDbsRZnjk',
			},
		],
		address: '62 RUE MOUFFETARD',
		bic: null,
		city: 'PARIS 5',
		dateCreated: '2018-10-03T12:15:02.720921Z',
		dateModifiedAtLastProvider: '2018-10-03T12:15:02.720911Z',
		iban: null,
		id: 'ALHA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'BREAKFAST AT YOUR PLACE',
		postalCode: '75005',
		siren: '793875030',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'AHBQ',
				modelName: 'UserOfferer',
				offererId: 'ALMQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-05T10:21:24.929474Z',
					departementCode: '93',
					email: 'julie.david@the-walrus.fr',
					firstName: 'Julie',
					isAdmin: false,
					lastName: 'DAVID ',
					phoneNumber: null,
					postalCode: '75010',
					publicName: 'DAVID',
				},
				userId: 'APXA',
				validationToken: null,
			},
		],
		address: '34 T RUE DE DUNKERQUE',
		bic: null,
		city: 'PARIS 10',
		dateCreated: '2018-10-05T10:21:24.932543Z',
		dateModifiedAtLastProvider: '2018-10-05T10:21:24.932536Z',
		iban: null,
		id: 'ALMQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'WALRUS',
		postalCode: '75010',
		siren: '799954383',
		thumbCount: 0,
		validationToken: '4z0jNi97l8aOt6hgZ9PpyMP1R5Y',
	},
	{
		UserOfferers: [
			{
				id: 'AHCQ',
				modelName: 'UserOfferer',
				offererId: 'ALNQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-05T13:29:16.057125Z',
					departementCode: '93',
					email: 'flavie.bitan@memorialdelashoah.org',
					firstName: 'Flavie',
					isAdmin: false,
					lastName: 'Bitan',
					phoneNumber: null,
					postalCode: '75004',
					publicName: 'M\u00e9morial de la Shoah',
				},
				userId: 'APYA',
				validationToken: null,
			},
		],
		address: '17 RUE GEOFFROY L ASNIER',
		bic: null,
		city: 'PARIS 4',
		dateCreated: '2018-10-05T13:29:16.058290Z',
		dateModifiedAtLastProvider: '2018-10-05T13:29:16.058284Z',
		iban: null,
		id: 'ALNQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MEMORIAL DE LA SHOAH',
		postalCode: '75004',
		siren: '784243784',
		thumbCount: 0,
		validationToken: '8LaMn4D-SGm2GGY6CWst5EVHdGQ',
	},
	{
		UserOfferers: [
			{
				id: 'AHDA',
				modelName: 'UserOfferer',
				offererId: 'AL8A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-05T14:35:34.271913Z',
					departementCode: '67',
					email: 'contact@3Jprod.eu',
					firstName: 'Arnaud',
					isAdmin: false,
					lastName: 'Stoltz',
					phoneNumber: null,
					postalCode: '67000',
					publicName: 'Asso3J',
				},
				userId: 'APYQ',
				validationToken: null,
			},
		],
		address: '11 ALLEE DE LA ROBERTSAU',
		bic: null,
		city: 'STRASBOURG',
		dateCreated: '2018-10-05T14:35:34.273354Z',
		dateModifiedAtLastProvider: '2018-10-05T14:35:34.273347Z',
		iban: null,
		id: 'AL8A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ASSOCIATION TROISIEME JOUR',
		postalCode: '67000',
		siren: '491538203',
		thumbCount: 0,
		validationToken: '53PxyhzJAfLyXb8Bf_Rc3yqKeCw',
	},
	{
		UserOfferers: [
			{
				id: 'AHDQ',
				modelName: 'UserOfferer',
				offererId: 'AL8Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-05T14:54:48.721844Z',
					departementCode: '67',
					email: 'virevolte67@gmail.com',
					firstName: 'Aurore',
					isAdmin: false,
					lastName: 'BUCHER',
					phoneNumber: null,
					postalCode: '67000',
					publicName: 'vir\u00e9volte',
				},
				userId: 'APZA',
				validationToken: null,
			},
		],
		address: '6 RUE STRAUSS DURKHEIM',
		bic: null,
		city: 'STRASBOURG',
		dateCreated: '2018-10-05T14:54:48.720100Z',
		dateModifiedAtLastProvider: '2018-10-05T14:54:48.720093Z',
		iban: null,
		id: 'AL8Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'VIREVOLTE',
		postalCode: '67000',
		siren: '800263998',
		thumbCount: 0,
		validationToken: 'TL4S7LpaDSaFONC65dmeWAhVRbk',
	},
	{
		UserOfferers: [
			{
				id: 'AHEA',
				modelName: 'UserOfferer',
				offererId: 'ALPA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-05T15:40:34.097374Z',
					departementCode: '26',
					email: 'librairieSaillans@gmail.com',
					firstName: 'Jean-Christophe',
					isAdmin: false,
					lastName: 'Faure',
					phoneNumber: null,
					postalCode: '26340',
					publicName: 'Librairie Saillans',
				},
				userId: 'APZQ',
				validationToken: null,
			},
		],
		address: '2 RUE DES ARCEAUX',
		bic: null,
		city: 'SAILLANS',
		dateCreated: '2018-10-05T15:40:34.102023Z',
		dateModifiedAtLastProvider: '2018-10-05T15:40:34.102018Z',
		iban: null,
		id: 'ALPA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LIBRAIRIE ALIMENTATION GENERALE',
		postalCode: '26340',
		siren: '823215686',
		thumbCount: 0,
		validationToken: 'iLJzKtvfBNBn5HcLY8F39O-hv_Y',
	},
	{
		UserOfferers: [
			{
				id: 'AHEQ',
				modelName: 'UserOfferer',
				offererId: 'ALPQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-05T15:56:56.760742Z',
					departementCode: '93',
					email: 'sabine.kokudua@mairie-aubervilliers.fr',
					firstName: 'Sabine',
					isAdmin: false,
					lastName: 'KOKUDUA',
					phoneNumber: null,
					postalCode: '93300',
					publicName: 'SabineK',
				},
				userId: 'AP2A',
				validationToken: null,
			},
		],
		address: '2 RUE DE LA COMMUNE DE PARIS',
		bic: null,
		city: 'AUBERVILLIERS',
		dateCreated: '2018-10-05T15:56:56.758338Z',
		dateModifiedAtLastProvider: '2018-10-05T15:56:56.758331Z',
		iban: null,
		id: 'ALPQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'COMMUNE D AUBERVILLIERS',
		postalCode: '93300',
		siren: '219300019',
		thumbCount: 0,
		validationToken: 'z-l_Yoh58PU-0YpU6c8wVIlzsPU',
	},
	{
		UserOfferers: [
			{
				id: 'AHGA',
				modelName: 'UserOfferer',
				offererId: 'ALRA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-06T07:26:57.839215Z',
					departementCode: '67',
					email: 'celine@dulcismelodia.com',
					firstName: 'C\u00e9line',
					isAdmin: false,
					lastName: 'Jacob',
					phoneNumber: null,
					postalCode: '67310',
					publicName: 'Dulcis Melodia',
				},
				userId: 'AP3Q',
				validationToken: null,
			},
		],
		address: '26 RUE DE COSSWILLER',
		bic: null,
		city: 'WASSELONNE',
		dateCreated: '2018-10-06T07:26:57.840362Z',
		dateModifiedAtLastProvider: '2018-10-06T07:26:57.840356Z',
		iban: null,
		id: 'ALRA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ENS MUSIQUE ANCIENNE DULCIS MELODIA',
		postalCode: '67310',
		siren: '522356591',
		thumbCount: 0,
		validationToken: 'mWlR0wgp7cfWJVJw3yun0j7ifWI',
	},
	{
		UserOfferers: [
			{
				id: 'AHGQ',
				modelName: 'UserOfferer',
				offererId: 'ALRQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-04T13:42:16.042568Z',
					departementCode: '93',
					email: 'collectif.librairies93@gmail.com',
					firstName: 'MORGANE',
					isAdmin: false,
					lastName: 'PAYOCK-MONTHE',
					phoneNumber: null,
					postalCode: '93500',
					publicName: 'Librairies93',
				},
				userId: 'APTA',
				validationToken: null,
			},
			{
				id: 'AHHA',
				modelName: 'UserOfferer',
				offererId: 'ALRQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-06T07:48:09.246477Z',
					departementCode: '93',
					email: 'malleauxhistoires@free.fr',
					firstName: 'MORGANE',
					isAdmin: false,
					lastName: 'PAYOCK-MONTHE',
					phoneNumber: null,
					postalCode: '93500',
					publicName: 'La Malle aux Histoires',
				},
				userId: 'AP4A',
				validationToken: 'RRR2-oRExJHbpffemiuDJ4HbLeg',
			},
		],
		address: '81 AVENUE JEAN LOLIVE',
		bic: 'BNPAFRPP',
		city: 'PANTIN',
		dateCreated: '2018-10-06T07:46:08.065319Z',
		dateModifiedAtLastProvider: '2018-10-06T07:46:08.065315Z',
		iban: 'FR7630004003770001005251668',
		id: 'ALRQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LE MONT BATCHA',
		postalCode: '93500',
		siren: '453555427',
		thumbCount: 0,
		validationToken: 'dROxbkXeLUVqUQbqYhug-l7Zs2Q',
	},
	{
		UserOfferers: [
			{
				id: 'AHHQ',
				modelName: 'UserOfferer',
				offererId: 'ALSA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-04T13:42:16.042568Z',
					departementCode: '93',
					email: 'collectif.librairies93@gmail.com',
					firstName: 'MORGANE',
					isAdmin: false,
					lastName: 'PAYOCK-MONTHE',
					phoneNumber: null,
					postalCode: '93500',
					publicName: 'Librairies93',
				},
				userId: 'APTA',
				validationToken: null,
			},
			{
				id: 'AHVQ',
				modelName: 'UserOfferer',
				offererId: 'ALSA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-10T07:40:13.776139Z',
					departementCode: '93',
					email: 'foliesdencrepavillons@gmail.com',
					firstName: 'sonia',
					isAdmin: false,
					lastName: 'sabino',
					phoneNumber: null,
					postalCode: '93320',
					publicName: 'Sakki Sonia',
				},
				userId: 'AQMQ',
				validationToken: 'kkTLxwv0xrNcbY31kwowBlJS3Pc',
			},
		],
		address: '1 ALLEE DE LA MAIN FERME',
		bic: null,
		city: 'LES PAVILLONS SOUS BOIS',
		dateCreated: '2018-10-06T07:54:21.862182Z',
		dateModifiedAtLastProvider: '2018-10-06T07:54:21.862177Z',
		iban: null,
		id: 'ALSA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LES PAGES DE GUILHERME',
		postalCode: '93320',
		siren: '831413513',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'AH9A',
				modelName: 'UserOfferer',
				offererId: 'ALVQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-06T08:37:10.658098Z',
					departementCode: '29',
					email: 'lespassagersdulivre@orange.fr',
					firstName: 'Les passagers du livre',
					isAdmin: false,
					lastName: 'Les passagers du livre',
					phoneNumber: null,
					postalCode: '29800',
					publicName: 'Les passagers du livre',
				},
				userId: 'AP4Q',
				validationToken: null,
			},
		],
		address: '28 RUE DE LA FONTAINE BLANCHE',
		bic: null,
		city: 'LANDERNEAU',
		dateCreated: '2018-10-06T08:37:10.659350Z',
		dateModifiedAtLastProvider: '2018-10-06T08:37:10.659345Z',
		iban: null,
		id: 'ALVQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LES PASSAGERS DU LIVRE',
		postalCode: '29800',
		siren: '794063958',
		thumbCount: 0,
		validationToken: '2Z5gv8pULVbSFHXca6rbj1UfqbI',
	},
	{
		UserOfferers: [
			{
				id: 'AH9Q',
				modelName: 'UserOfferer',
				offererId: 'ALWA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-06T12:55:24.870997Z',
					departementCode: '43',
					email: 'simon@greenpiste-records.com',
					firstName: 'Simon',
					isAdmin: false,
					lastName: 'Kessler',
					phoneNumber: null,
					postalCode: '43230',
					publicName: 'Green Piste Records',
				},
				userId: 'AP5Q',
				validationToken: null,
			},
		],
		address: '1 RUE DE LA CHEVRERIE',
		bic: null,
		city: 'PAULHAGUET',
		dateCreated: '2018-10-06T12:55:24.869405Z',
		dateModifiedAtLastProvider: '2018-10-06T12:55:24.869398Z',
		iban: null,
		id: 'ALWA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'GREEN PISTE RECORDS',
		postalCode: '43230',
		siren: '517456539',
		thumbCount: 0,
		validationToken: 'rnmPERgO9mdfJ5d6DssUNnqLXLA',
	},
	{
		UserOfferers: [
			{
				id: 'A9CQ',
				modelName: 'UserOfferer',
				offererId: 'AMWQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-12T08:12:51.976382Z',
					departementCode: '26',
					email: 'librairiedescordeliers@gmail.com',
					firstName: 'fran\u00e7ois',
					isAdmin: false,
					lastName: 'reynaud',
					phoneNumber: null,
					postalCode: '26100',
					publicName: 'cordeliers',
				},
				userId: 'AQ2A',
				validationToken: null,
			},
		],
		address: '7 COTE DES CORDELIERS',
		bic: null,
		city: 'ROMANS SUR ISERE',
		dateCreated: '2018-10-12T08:12:51.973214Z',
		dateModifiedAtLastProvider: '2018-10-12T08:12:51.973200Z',
		iban: null,
		id: 'AMWQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LIBRAIRIE DES CORDELIERS',
		postalCode: '26100',
		siren: '512581208',
		thumbCount: 0,
		validationToken: 'zdEOS39mLUIBWUqGz_621hdCblM',
	},
	{
		UserOfferers: [
			{
				id: 'A9UA',
				modelName: 'UserOfferer',
				offererId: 'AN9A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-16T20:08:31.065419Z',
					departementCode: '34',
					email: 'sportingkaratemontpellier@gmail.com',
					firstName: 'ABDELILAH',
					isAdmin: false,
					lastName: 'RGHIOUI',
					phoneNumber: null,
					postalCode: '34000',
					publicName: 'SPORTING KARATE MONTPELLIER',
				},
				userId: 'ARKQ',
				validationToken: null,
			},
		],
		address: '1110 AVENUE DE SAINT MAUR',
		bic: null,
		city: 'MONTPELLIER',
		dateCreated: '2018-10-16T20:08:31.068022Z',
		dateModifiedAtLastProvider: '2018-10-16T20:08:31.067983Z',
		iban: null,
		id: 'AN9A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'SPORTING KARATE MONTPELLIER',
		postalCode: '34000',
		siren: '839663739',
		thumbCount: 0,
		validationToken: 'SG1jc4iESYh6Kw4cyYrYvzuoyI8',
	},
	{
		UserOfferers: [
			{
				id: 'AJUA',
				modelName: 'UserOfferer',
				offererId: 'A88Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T07:27:52.539973Z',
					departementCode: '93',
					email: 'jord.ledortz@gmail.com',
					firstName: 'jord',
					isAdmin: false,
					lastName: 'le dortz',
					phoneNumber: null,
					postalCode: '75020',
					publicName: 'jord',
				},
				userId: 'ASKA',
				validationToken: null,
			},
		],
		address: '14 RUE DES CENDRIERS',
		bic: null,
		city: 'PARIS 20',
		dateCreated: '2018-10-25T07:27:52.541954Z',
		dateModifiedAtLastProvider: '2018-10-25T07:27:52.541888Z',
		iban: null,
		id: 'A88Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MONSIEUR JORD LE DORTZ',
		postalCode: '75020',
		siren: '811570407',
		thumbCount: 0,
		validationToken: 'GNvdOD3TRw8ih1GBPiox_6cc6Mc',
	},
	{
		UserOfferers: [
			{
				id: 'AJWQ',
				modelName: 'UserOfferer',
				offererId: 'A8SQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T14:12:48.368692Z',
					departementCode: '45',
					email: 'levox@levox.fr',
					firstName: 'Jo\u00ebl ',
					isAdmin: false,
					lastName: 'Riflet',
					phoneNumber: null,
					postalCode: '45220',
					publicName: 'Jo\u00ebl',
				},
				userId: 'ASMQ',
				validationToken: null,
			},
		],
		address: '28 PLACE DU VIEUX MARCHE',
		bic: null,
		city: 'CHATEAU RENARD',
		dateCreated: '2018-10-25T14:12:48.363119Z',
		dateModifiedAtLastProvider: '2018-10-25T14:12:48.363112Z',
		iban: null,
		id: 'A8SQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'VOX POPULI',
		postalCode: '45220',
		siren: '432900744',
		thumbCount: 0,
		validationToken: 'eVPC3doar2HlctbPiC_nObHqrVQ',
	},
	{
		UserOfferers: [
			{
				id: 'AJXA',
				modelName: 'UserOfferer',
				offererId: 'A8UQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T14:22:55.305921Z',
					departementCode: '24',
					email: 'julien.robillard@cine-passion24.com',
					firstName: 'JULIEN',
					isAdmin: false,
					lastName: 'ROBILLARD',
					phoneNumber: null,
					postalCode: '24110',
					publicName: 'CINE PASSION 24',
				},
				userId: 'ASNA',
				validationToken: null,
			},
		],
		address: '8 RUE AMIRAL COURBET',
		bic: null,
		city: 'SAINT ASTIER',
		dateCreated: '2018-10-25T14:22:55.307963Z',
		dateModifiedAtLastProvider: '2018-10-25T14:22:55.307957Z',
		iban: null,
		id: 'A8UQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ASSOCIATION CINE PASSION EN PERIGORD',
		postalCode: '24110',
		siren: '411131626',
		thumbCount: 0,
		validationToken: 'IEIfaDZsTCWcYdOKqmcOJfgzcPU',
	},
	{
		UserOfferers: [
			{
				id: 'AJYQ',
				modelName: 'UserOfferer',
				offererId: 'A8WQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T14:42:11.624387Z',
					departementCode: '38',
					email: 'cinema.oron@free.fr',
					firstName: 'JOFFREY',
					isAdmin: false,
					lastName: 'FORMONT',
					phoneNumber: null,
					postalCode: '38270',
					publicName: "l'Oron-Beaurepaire",
				},
				userId: 'AS8Q',
				validationToken: null,
			},
		],
		address: '2 AVENUE LOUIS MICHEL VILLAZ',
		bic: null,
		city: 'BEAUREPAIRE',
		dateCreated: '2018-10-25T14:42:11.621151Z',
		dateModifiedAtLastProvider: '2018-10-25T14:42:11.621125Z',
		iban: null,
		id: 'A8WQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MONSIEUR JOFFREY FORMONT',
		postalCode: '38270',
		siren: '483628137',
		thumbCount: 0,
		validationToken: '8r2OB-wY1HCTcvAPDrVOthPB0a8',
	},
	{
		UserOfferers: [
			{
				id: 'AJZA',
				modelName: 'UserOfferer',
				offererId: 'A8XA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T14:49:09.732934Z',
					departementCode: '64',
					email: 'cineluz.64500@gmail.com',
					firstName: 'Xabi',
					isAdmin: false,
					lastName: 'GARAT',
					phoneNumber: null,
					postalCode: '64500',
					publicName: 'Cin\u00e9ma Le S\u00e9lect',
				},
				userId: 'ASPA',
				validationToken: null,
			},
		],
		address: '29 BOULEVARD VICTOR HUGO',
		bic: null,
		city: 'SAINT JEAN DE LUZ',
		dateCreated: '2018-10-25T14:49:09.740344Z',
		dateModifiedAtLastProvider: '2018-10-25T14:49:09.740339Z',
		iban: null,
		id: 'A8XA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LES ECRANS LUZIENS',
		postalCode: '64500',
		siren: '495106148',
		thumbCount: 0,
		validationToken: 'xq3zI6Pcyg81jJXABydDwyVVdAk',
	},
	{
		UserOfferers: [
			{
				id: 'AJZQ',
				modelName: 'UserOfferer',
				offererId: 'A8XQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T15:39:27.912030Z',
					departementCode: '19',
					email: 'passculture@veocinemas.fr',
					firstName: 'Jean',
					isAdmin: false,
					lastName: 'Villa',
					phoneNumber: null,
					postalCode: '19300',
					publicName: 'V\u00e9o Cin\u00e9mas',
				},
				userId: 'ASPQ',
				validationToken: null,
			},
		],
		address: 'RUE DE SARRAN',
		bic: null,
		city: 'EGLETONS',
		dateCreated: '2018-10-25T15:39:27.909382Z',
		dateModifiedAtLastProvider: '2018-10-25T15:39:27.909375Z',
		iban: null,
		id: 'A8XQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'VEO CINEMAS',
		postalCode: '19300',
		siren: '399691922',
		thumbCount: 0,
		validationToken: '_axZ5lZ9El1bZm9tnz510QqDz5U',
	},
	{
		UserOfferers: [
			{
				id: 'AJ2A',
				modelName: 'UserOfferer',
				offererId: 'A8YA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T15:39:28.547582Z',
					departementCode: '53',
					email: 'contact@boxonquichotte.fr',
					firstName: 'Philippe',
					isAdmin: false,
					lastName: 'Roger',
					phoneNumber: null,
					postalCode: '53190',
					publicName: 'DVD Donquichotte',
				},
				userId: 'ASQA',
				validationToken: null,
			},
		],
		address: '10 RUE DE NORMANDIE',
		bic: null,
		city: 'FOUGEROLLES DU PLESSIS',
		dateCreated: '2018-10-25T15:39:28.541130Z',
		dateModifiedAtLastProvider: '2018-10-25T15:39:28.541120Z',
		iban: null,
		id: 'A8YA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MONSIEUR PHILIPPE ROGER',
		postalCode: '53190',
		siren: '433335262',
		thumbCount: 0,
		validationToken: 'qL2Efd4D8twfh9YQhqTkNYZyKu0',
	},
	{
		UserOfferers: [
			{
				id: 'AJ2Q',
				modelName: 'UserOfferer',
				offererId: 'A8YQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T15:39:27.912030Z',
					departementCode: '19',
					email: 'passculture@veocinemas.fr',
					firstName: 'Jean',
					isAdmin: false,
					lastName: 'Villa',
					phoneNumber: null,
					postalCode: '19300',
					publicName: 'V\u00e9o Cin\u00e9mas',
				},
				userId: 'ASPQ',
				validationToken: null,
			},
		],
		address: 'RUE DE SARRAN',
		bic: null,
		city: 'EGLETONS',
		dateCreated: '2018-10-25T15:40:04.334443Z',
		dateModifiedAtLastProvider: '2018-10-25T15:40:04.334435Z',
		iban: null,
		id: 'A8YQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'VEO MURET',
		postalCode: '19300',
		siren: '510604291',
		thumbCount: 0,
		validationToken: 'PLvyFbRIiHlaM1G6xzWfv6cnA0M',
	},
	{
		UserOfferers: [
			{
				id: 'AJ3A',
				modelName: 'UserOfferer',
				offererId: 'A8ZA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T15:39:27.912030Z',
					departementCode: '19',
					email: 'passculture@veocinemas.fr',
					firstName: 'Jean',
					isAdmin: false,
					lastName: 'Villa',
					phoneNumber: null,
					postalCode: '19300',
					publicName: 'V\u00e9o Cin\u00e9mas',
				},
				userId: 'ASPQ',
				validationToken: null,
			},
		],
		address: 'RUE DE SARRAN',
		bic: null,
		city: 'EGLETONS',
		dateCreated: '2018-10-25T15:40:58.495844Z',
		dateModifiedAtLastProvider: '2018-10-25T15:40:58.495833Z',
		iban: null,
		id: 'A8ZA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'VEO TULLE',
		postalCode: '19300',
		siren: '797825940',
		thumbCount: 0,
		validationToken: 'XxrXFfdtJzSXLUWEegylUxY99aA',
	},
	{
		UserOfferers: [
			{
				id: 'AJ3Q',
				modelName: 'UserOfferer',
				offererId: 'A8ZQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T15:39:27.912030Z',
					departementCode: '19',
					email: 'passculture@veocinemas.fr',
					firstName: 'Jean',
					isAdmin: false,
					lastName: 'Villa',
					phoneNumber: null,
					postalCode: '19300',
					publicName: 'V\u00e9o Cin\u00e9mas',
				},
				userId: 'ASPQ',
				validationToken: null,
			},
		],
		address: 'RUE DE SARRAN',
		bic: null,
		city: 'EGLETONS',
		dateCreated: '2018-10-25T15:41:35.324795Z',
		dateModifiedAtLastProvider: '2018-10-25T15:41:35.324783Z',
		iban: null,
		id: 'A8ZQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'VEO URFOL SAINT CHAMOND',
		postalCode: '19300',
		siren: '831155569',
		thumbCount: 0,
		validationToken: 'v1Ig-ALrEWEA86QeY3fRAiCbRrM',
	},
	{
		UserOfferers: [
			{
				id: 'AJ5A',
				modelName: 'UserOfferer',
				offererId: 'A82Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-25T19:40:09.370574Z',
					departementCode: '33',
					email: 'info-ctc@orange.fr',
					firstName: 'jose',
					isAdmin: false,
					lastName: 'sousa esilva',
					phoneNumber: null,
					postalCode: '33480',
					publicName: 'ctc',
				},
				userId: 'ASRQ',
				validationToken: null,
			},
		],
		address: '13 ALLEE DE LA BRISE',
		bic: null,
		city: 'SAINTE HELENE',
		dateCreated: '2018-10-25T19:40:09.374153Z',
		dateModifiedAtLastProvider: '2018-10-25T19:40:09.374144Z',
		iban: null,
		id: 'A82Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'CONCEPT ET TECHNIQUE CINEMATOGRAPHIQUE',
		postalCode: '33480',
		siren: '788714228',
		thumbCount: 0,
		validationToken: 'Q55X_4KiH4vKkH6j_FgQ2p-c8xA',
	},
	{
		UserOfferers: [
			{
				id: 'AJ6A',
				modelName: 'UserOfferer',
				offererId: 'A83Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-26T06:49:50.012904Z',
					departementCode: '86',
					email: 'mairie-cinema@orange.fr',
					firstName: 'S\u00e9bastien',
					isAdmin: false,
					lastName: 'Olalde',
					phoneNumber: null,
					postalCode: '86270',
					publicName: 'Cin\u00e9ma Le Kerlou\u00ebt',
				},
				userId: 'ASSQ',
				validationToken: null,
			},
		],
		address: 'AVENUE GEORGES DELOFFRE',
		bic: null,
		city: 'LA ROCHE POSAY',
		dateCreated: '2018-10-26T06:49:50.000564Z',
		dateModifiedAtLastProvider: '2018-10-26T06:49:50.000551Z',
		iban: null,
		id: 'A83Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'COMPLEXE COMMERCIAL DE LA ROCHE POSAY',
		postalCode: '86270',
		siren: '331152991',
		thumbCount: 0,
		validationToken: '2-VVmbZzYxyihhZvHdAweawLybY',
	},
	{
		UserOfferers: [
			{
				id: 'AJ7A',
				modelName: 'UserOfferer',
				offererId: 'A84Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-26T07:16:36.972358Z',
					departementCode: '47',
					email: 'administration@lesmontreursdimages.com',
					firstName: 'SYLVAIN',
					isAdmin: false,
					lastName: 'PHILIPPON',
					phoneNumber: null,
					postalCode: '47000',
					publicName: "Montreurs d'Images",
				},
				userId: 'ASTQ',
				validationToken: null,
			},
		],
		address: '12 RUE JULES FERRY',
		bic: null,
		city: 'AGEN',
		dateCreated: '2018-10-26T07:16:36.970347Z',
		dateModifiedAtLastProvider: '2018-10-26T07:16:36.970336Z',
		iban: null,
		id: 'A84Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LES MONTREURS D IMAGES',
		postalCode: '47000',
		siren: '403755648',
		thumbCount: 0,
		validationToken: '_jhDAF7rKgdVkZwMVgmmKX66MGQ',
	},
	{
		UserOfferers: [
			{
				id: 'AKAA',
				modelName: 'UserOfferer',
				offererId: 'A85Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-10-26T07:30:46.752684Z',
					departementCode: '76',
					email: 'herve.aguillard@noecinemas.com',
					firstName: 'HERVE',
					isAdmin: false,
					lastName: 'AGUILLARD',
					phoneNumber: null,
					postalCode: '76500',
					publicName: 'OMNIA ROUEN',
				},
				userId: 'ASUQ',
				validationToken: null,
			},
		],
		address: 'SQUARE GRIMOIN SAMSON',
		bic: null,
		city: 'ELBEUF',
		dateCreated: '2018-10-26T07:30:46.755370Z',
		dateModifiedAtLastProvider: '2018-10-26T07:30:46.755362Z',
		iban: null,
		id: 'A85Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'NOE CINEMAS ROUEN',
		postalCode: '76500',
		siren: '518448501',
		thumbCount: 0,
		validationToken: 'NGx6Bwbh4YVyoDQfp3gHFq3DKOk',
	},
	{
		UserOfferers: [
			{
				id: 'ALCA',
				modelName: 'UserOfferer',
				offererId: 'AQFA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-05T20:57:47.450710Z',
					departementCode: '67',
					email: 'familangues@gmail.com',
					firstName: 'FAMILANGUES',
					isAdmin: false,
					lastName: 'Association',
					phoneNumber: null,
					postalCode: '67000',
					publicName: 'Association FAMILANGUES',
				},
				userId: 'ATXQ',
				validationToken: null,
			},
		],
		address: '35 RUE VAUBAN',
		bic: null,
		city: 'STRASBOURG',
		dateCreated: '2018-11-05T20:57:47.454993Z',
		dateModifiedAtLastProvider: '2018-11-05T20:57:47.454979Z',
		iban: null,
		id: 'AQFA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'FAMILANGUES',
		postalCode: '67000',
		siren: '803617836',
		thumbCount: 0,
		validationToken: 'oyIatTF0uHdqj2KzU2ebYxK6Qr8',
	},
	{
		UserOfferers: [
			{
				id: 'ALHQ',
				modelName: 'UserOfferer',
				offererId: 'AQKA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-06T22:29:18.570653Z',
					departementCode: '24',
					email: 'manege24-33@hotmail.fr',
					firstName: 'veronique',
					isAdmin: false,
					lastName: 'gouband',
					phoneNumber: null,
					postalCode: '24100',
					publicName: 'manegemusic',
				},
				userId: 'AT5A',
				validationToken: null,
			},
		],
		address: 'LIEU DIT LES BERNABROTS',
		bic: null,
		city: 'BERGERAC',
		dateCreated: '2018-11-06T22:29:18.568175Z',
		dateModifiedAtLastProvider: '2018-11-06T22:29:18.568164Z',
		iban: null,
		id: 'AQKA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MANEGE',
		postalCode: '24100',
		siren: '490209392',
		thumbCount: 0,
		validationToken: 'F6DdN5aRoRtJNatWAv4g9KXQEUw',
	},
	{
		UserOfferers: [
			{
				id: 'ALSA',
				modelName: 'UserOfferer',
				offererId: 'AQUA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-08T13:08:03.442103Z',
					departementCode: '45',
					email: 'michelferry@mac.com',
					firstName: 'Michel',
					isAdmin: false,
					lastName: 'FERRY',
					phoneNumber: null,
					postalCode: '45000',
					publicName: 'les carmes',
				},
				userId: 'AUHQ',
				validationToken: null,
			},
		],
		address: '7 RUE DES CARMES',
		bic: null,
		city: 'ORLEANS',
		dateCreated: '2018-11-08T13:08:03.447232Z',
		dateModifiedAtLastProvider: '2018-11-08T13:08:03.447221Z',
		iban: null,
		id: 'AQUA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LES CARMELITES',
		postalCode: '45000',
		siren: '798413696',
		thumbCount: 0,
		validationToken: 'VkJC1VBC9Iw70NHwZ02-oMX6u_4',
	},
	{
		UserOfferers: [
			{
				id: 'ALUQ',
				modelName: 'UserOfferer',
				offererId: 'AQWQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-09T08:19:10.485075Z',
					departementCode: '68',
					email: 'olivier.saenger@gmail.com',
					firstName: 'Olivier',
					isAdmin: false,
					lastName: 'SAENGER',
					phoneNumber: null,
					postalCode: '68500',
					publicName: 'o.saenger',
				},
				userId: 'AUKA',
				validationToken: null,
			},
		],
		address: '1 RUE DE L HOPITAL',
		bic: null,
		city: 'GUEBWILLER',
		dateCreated: '2018-11-09T08:19:10.487104Z',
		dateModifiedAtLastProvider: '2018-11-09T08:19:10.487087Z',
		iban: null,
		id: 'AQWQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'CONSEIL DEPARTEMENTAL MUSIQUE ET CULTU',
		postalCode: '68500',
		siren: '778903641',
		thumbCount: 0,
		validationToken: 'l7bRnWBp9OdQW8zsqcciYcYnCp8',
	},
	{
		UserOfferers: [
			{
				id: 'ALWA',
				modelName: 'UserOfferer',
				offererId: 'AQYA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-09T12:49:57.659504Z',
					departementCode: '93',
					email: 'emeline@aquiletour95.com',
					firstName: 'Arnould',
					isAdmin: false,
					lastName: 'Emeline',
					phoneNumber: null,
					postalCode: '95440',
					publicName: 'EmelineAQLT',
				},
				userId: 'AULQ',
				validationToken: null,
			},
		],
		address: 'PLACE DE LA MAIRIE',
		bic: null,
		city: 'ECOUEN',
		dateCreated: '2018-11-09T12:49:57.657371Z',
		dateModifiedAtLastProvider: '2018-11-09T12:49:57.657360Z',
		iban: null,
		id: 'AQYA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'A QUI LE TOUR',
		postalCode: '95440',
		siren: '493153415',
		thumbCount: 0,
		validationToken: 'QkWfoQBZP6s1tSrC25XbAXD2NNM',
	},
	{
		UserOfferers: [
			{
				id: 'AL6A',
				modelName: 'UserOfferer',
				offererId: 'ARAA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-13T08:26:50.360248Z',
					departementCode: '21',
					email: 'h.reithler@alternatives-economiques.fr',
					firstName: 'H\u00e9l\u00e8ne',
					isAdmin: false,
					lastName: 'Reithler',
					phoneNumber: null,
					postalCode: '21800',
					publicName: 'Alternatives Economiques',
				},
				userId: 'AUUA',
				validationToken: null,
			},
		],
		address: '12 RUE DU CAP VERT',
		bic: null,
		city: 'QUETIGNY',
		dateCreated: '2018-11-13T08:26:50.366528Z',
		dateModifiedAtLastProvider: '2018-11-13T08:26:50.366515Z',
		iban: null,
		id: 'ARAA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ALTERNATIVES ECONOMIQUES SOC COOP TRAV',
		postalCode: '21800',
		siren: '330394479',
		thumbCount: 0,
		validationToken: '0563FVtAhHRV-FWbkP0mXJKNIyQ',
	},
	{
		UserOfferers: [
			{
				id: 'AL6Q',
				modelName: 'UserOfferer',
				offererId: 'ARAQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-13T08:36:08.654379Z',
					departementCode: '33',
					email: 'p.vettese@cultura.fr',
					firstName: 'Philippe',
					isAdmin: false,
					lastName: 'VETTESE',
					phoneNumber: null,
					postalCode: '33700',
					publicName: 'Philippe',
				},
				userId: 'AUUQ',
				validationToken: null,
			},
		],
		address: '17 RUE ARCHIMEDE',
		bic: null,
		city: 'MERIGNAC',
		dateCreated: '2018-11-13T08:36:08.651592Z',
		dateModifiedAtLastProvider: '2018-11-13T08:36:08.651567Z',
		iban: null,
		id: 'ARAQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'SOCULTUR',
		postalCode: '33700',
		siren: '519780795',
		thumbCount: 0,
		validationToken: 'eFzKdLP2PH8vp2vukBWqJs-ciXM',
	},
	{
		UserOfferers: [
			{
				id: 'AMCQ',
				modelName: 'UserOfferer',
				offererId: 'AREA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-14T09:22:45.205809Z',
					departementCode: '52',
					email: 'v.villette@ville-nogentsurmarne.fr',
					firstName: 'Vincent',
					isAdmin: false,
					lastName: 'VILLETTE',
					phoneNumber: null,
					postalCode: '52800',
					publicName: 'Nogent-sur-Marne',
				},
				userId: 'AUYQ',
				validationToken: null,
			},
		],
		address: 'PL DU GENERAL CHARLES DE GAULLE',
		bic: null,
		city: 'NOGENT',
		dateCreated: '2018-11-14T09:22:45.199862Z',
		dateModifiedAtLastProvider: '2018-11-14T09:22:45.199854Z',
		iban: null,
		id: 'AREA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'COMMUNE DE NOGENT',
		postalCode: '52800',
		siren: '215202532',
		thumbCount: 0,
		validationToken: 'SDA5DWjkJ2CxFf9694fCSssqcaA',
	},
	{
		UserOfferers: [
			{
				id: 'AMFA',
				modelName: 'UserOfferer',
				offererId: 'AR9A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-14T14:48:20.393595Z',
					departementCode: '92',
					email: 'selmadesmot@gmail.com',
					firstName: 'selma',
					isAdmin: false,
					lastName: 'desmot',
					phoneNumber: null,
					postalCode: '92200',
					publicName: 'BooKaaZ',
				},
				userId: 'AU3A',
				validationToken: null,
			},
		],
		address: '176 AVENUE CHARLES DE GAULLE',
		bic: null,
		city: 'NEUILLY SUR SEINE',
		dateCreated: '2018-11-14T14:48:20.397120Z',
		dateModifiedAtLastProvider: '2018-11-14T14:48:20.397114Z',
		iban: null,
		id: 'AR9A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'BOOKAAZ',
		postalCode: '92200',
		siren: '828893537',
		thumbCount: 0,
		validationToken: 'EXlAOyd6f_DkG9-_o2pPVNDSqgc',
	},
	{
		UserOfferers: [
			{
				id: 'AMFQ',
				modelName: 'UserOfferer',
				offererId: 'AR9Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-14T16:42:29.248237Z',
					departementCode: '93',
					email: 'vfernandez@gofluent.com',
					firstName: 'Victoria',
					isAdmin: false,
					lastName: 'Fernandez',
					phoneNumber: null,
					postalCode: '75009',
					publicName: 'Vicky',
				},
				userId: 'AU3Q',
				validationToken: null,
			},
		],
		address: '3 B RUE DE LA CHAUSSEE D ANTIN',
		bic: null,
		city: 'PARIS 9',
		dateCreated: '2018-11-14T16:42:29.252349Z',
		dateModifiedAtLastProvider: '2018-11-14T16:42:29.252340Z',
		iban: null,
		id: 'AR9Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'GOFLUENT',
		postalCode: '75009',
		siren: '433467529',
		thumbCount: 0,
		validationToken: '_6-X0UcmWO92vVFdrqfCfeG0m2g',
	},
	{
		UserOfferers: [
			{
				id: 'AM9A',
				modelName: 'UserOfferer',
				offererId: 'ARKQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-14T20:54:59.706963Z',
					departementCode: '93',
					email: 'lolilol123@outlook.fr',
					firstName: 'Delhia',
					isAdmin: false,
					lastName: 'Wanderstein',
					phoneNumber: null,
					postalCode: '75012',
					publicName: 'lolilol.32',
				},
				userId: 'AU6A',
				validationToken: null,
			},
		],
		address: '94 COURS DE VINCENNES',
		bic: null,
		city: 'PARIS 12',
		dateCreated: '2018-11-14T20:54:59.709692Z',
		dateModifiedAtLastProvider: '2018-11-14T20:54:59.709685Z',
		iban: null,
		id: 'ARKQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'INSTITUT NOUV TECHNOLOGIES INFORMATIQU',
		postalCode: '75012',
		siren: '448911511',
		thumbCount: 0,
		validationToken: 'igO3QpUaxrSg_w4bqTyMQw3nRlE',
	},
	{
		UserOfferers: [
			{
				id: 'AMKA',
				modelName: 'UserOfferer',
				offererId: 'ARNA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-15T13:42:23.091028Z',
					departementCode: '35',
					email: 'contact@courtsenbetton.com',
					firstName: 'Coline',
					isAdmin: false,
					lastName: 'GUEGUEN',
					phoneNumber: null,
					postalCode: '35830',
					publicName: 'Courts en Betton',
				},
				userId: 'AVAA',
				validationToken: null,
			},
		],
		address: '6 ALLEE DES MIMOSAS',
		bic: null,
		city: 'BETTON',
		dateCreated: '2018-11-15T13:42:23.092634Z',
		dateModifiedAtLastProvider: '2018-11-15T13:42:23.092625Z',
		iban: null,
		id: 'ARNA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'COURTS EN BETTON',
		postalCode: '35830',
		siren: '750359093',
		thumbCount: 0,
		validationToken: 'xnYtAZibaeEd8Wvm336rg71iG7g',
	},
	{
		UserOfferers: [
			{
				id: 'AMNQ',
				modelName: 'UserOfferer',
				offererId: 'ARRA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-16T21:37:45.752536Z',
					departementCode: '93',
					email: 'raphael@interlettre.media',
					firstName: 'Raphael',
					isAdmin: false,
					lastName: 'MARTIN',
					phoneNumber: null,
					postalCode: '78000',
					publicName: 'raphaelm',
				},
				userId: 'AVEA',
				validationToken: null,
			},
		],
		address: '24 RUE DE VERGENNES',
		bic: null,
		city: 'VERSAILLES',
		dateCreated: '2018-11-16T21:37:45.750818Z',
		dateModifiedAtLastProvider: '2018-11-16T21:37:45.750809Z',
		iban: null,
		id: 'ARRA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MONSIEUR RAPHAEL MARTIN',
		postalCode: '78000',
		siren: '818077042',
		thumbCount: 0,
		validationToken: 'piZ4jQqfSp5fTnfHdDc0BYUXPWM',
	},
	{
		UserOfferers: [
			{
				id: 'AM8A',
				modelName: 'UserOfferer',
				offererId: 'ARRQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-17T07:08:36.150362Z',
					departementCode: '59',
					email: 'erik.mikula784@orange.fr',
					firstName: 'Corine',
					isAdmin: false,
					lastName: 'Pagny',
					phoneNumber: null,
					postalCode: '59820',
					publicName: 'Pagny',
				},
				userId: 'AVEQ',
				validationToken: null,
			},
		],
		address: 'RUE LEON BLUM',
		bic: null,
		city: 'GRAVELINES',
		dateCreated: '2018-11-17T07:08:36.151316Z',
		dateModifiedAtLastProvider: '2018-11-17T07:08:36.151311Z',
		iban: null,
		id: 'ARRQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'ART IN THE JUNGLE',
		postalCode: '59820',
		siren: '822007753',
		thumbCount: 0,
		validationToken: 'J2oKfrDFwEcTnQP_VP4aIrXEX9Q',
	},
	{
		UserOfferers: [
			{
				id: 'AM3A',
				modelName: 'UserOfferer',
				offererId: 'AR4A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T09:23:39.752395Z',
					departementCode: '59',
					email: 'passeculture@delitoon.com',
					firstName: 'Hyung-Rae',
					isAdmin: false,
					lastName: 'Kim',
					phoneNumber: null,
					postalCode: '59800',
					publicName: 'delitoon',
				},
				userId: 'AVRQ',
				validationToken: null,
			},
			{
				id: 'AM3Q',
				modelName: 'UserOfferer',
				offererId: 'AR4A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T09:44:18.012606Z',
					departementCode: '59',
					email: 'passculture@delitoon.com',
					firstName: 'Hyung-Rae',
					isAdmin: false,
					lastName: 'Kim',
					phoneNumber: null,
					postalCode: '59800',
					publicName: 'delitoon',
				},
				userId: 'AVSA',
				validationToken: '67THOPirZm4aerNUbdSEIvuQtT0',
			},
		],
		address: '12 B RUE DES TOURS',
		bic: null,
		city: 'LILLE',
		dateCreated: '2018-11-23T09:23:39.732889Z',
		dateModifiedAtLastProvider: '2018-11-23T09:23:39.732881Z',
		iban: null,
		id: 'AR4A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'WOSMU',
		postalCode: '59800',
		siren: '812871598',
		thumbCount: 0,
		validationToken: null,
	},
	{
		UserOfferers: [
			{
				id: 'AM5A',
				modelName: 'UserOfferer',
				offererId: 'AR6A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T11:56:53.754652Z',
					departementCode: '93',
					email: 't.vartanian@lalterego.fr',
					firstName: 'Tristan',
					isAdmin: false,
					lastName: 'VARTANIAN',
					phoneNumber: null,
					postalCode: '75015',
					publicName: 'Tristan',
				},
				userId: 'AVTQ',
				validationToken: null,
			},
		],
		address: '204 B RUE DE LA CROIX NIVERT',
		bic: null,
		city: 'PARIS 15',
		dateCreated: '2018-11-23T11:56:53.755687Z',
		dateModifiedAtLastProvider: '2018-11-23T11:56:53.755681Z',
		iban: null,
		id: 'AR6A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'AGENCE PRESSES JEUNE',
		postalCode: '75015',
		siren: '825081664',
		thumbCount: 0,
		validationToken: 'KY3zJ_1cPVgaKWtYepoqQUEK3K8',
	},
	{
		UserOfferers: [
			{
				id: 'AM5Q',
				modelName: 'UserOfferer',
				offererId: 'AR6Q',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T12:17:59.008128Z',
					departementCode: '77',
					email: 'blocquaux.megarama@gmail.com',
					firstName: 'Villeneuve',
					isAdmin: false,
					lastName: 'Megarama',
					phoneNumber: null,
					postalCode: '77480',
					publicName: 'Megarama Villeneuve',
				},
				userId: 'AVUA',
				validationToken: null,
			},
		],
		address: '23 RUE DES FILOIRS',
		bic: null,
		city: 'BRAY SUR SEINE',
		dateCreated: '2018-11-23T12:17:59.009798Z',
		dateModifiedAtLastProvider: '2018-11-23T12:17:59.009787Z',
		iban: null,
		id: 'AR6Q',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LES IMAGES',
		postalCode: '77480',
		siren: '775670664',
		thumbCount: 0,
		validationToken: 'lme5z6IRKPbAGaiiZFzubmny_Hg',
	},
	{
		UserOfferers: [
			{
				id: 'AM6A',
				modelName: 'UserOfferer',
				offererId: 'AR7A',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T13:11:08.792675Z',
					departementCode: '34',
					email: 'erwan.villegier@gmail.com',
					firstName: 'Erwan',
					isAdmin: false,
					lastName: 'Villegier',
					phoneNumber: null,
					postalCode: '34170',
					publicName: 'Pandore',
				},
				userId: 'AVUQ',
				validationToken: null,
			},
		],
		address: '351 AV DU MAL DE LATTRE DE TASSIGNY',
		bic: null,
		city: 'CASTELNAU LE LEZ',
		dateCreated: '2018-11-23T13:11:08.790571Z',
		dateModifiedAtLastProvider: '2018-11-23T13:11:08.790562Z',
		iban: null,
		id: 'AR7A',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'LYCEE POLYVALENT GEORGES POMPIDOU',
		postalCode: '34170',
		siren: '193400017',
		thumbCount: 0,
		validationToken: 'YTKySSpjGkZ-a0C6LOK9q1Xx56U',
	},
	{
		UserOfferers: [
			{
				id: 'AM6Q',
				modelName: 'UserOfferer',
				offererId: 'ASAA',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T15:21:38.355119Z',
					departementCode: '59',
					email: 'mawinapiking973@gmail.com',
					firstName: 'atanso',
					isAdmin: false,
					lastName: 'ruben',
					phoneNumber: null,
					postalCode: '59000',
					publicName: 'MAWINA PIKING',
				},
				userId: 'AVVA',
				validationToken: null,
			},
		],
		address: '18 RUE VAN DYCK',
		bic: null,
		city: 'LILLE',
		dateCreated: '2018-11-23T15:21:38.356848Z',
		dateModifiedAtLastProvider: '2018-11-23T15:21:38.356838Z',
		iban: null,
		id: 'ASAA',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'MAWINA PIKING',
		postalCode: '59000',
		siren: '508465804',
		thumbCount: 0,
		validationToken: 'HtEjNgq9jkuP0nuh1Oxsyc40Tok',
	},
	{
		UserOfferers: [
			{
				id: 'AM7A',
				modelName: 'UserOfferer',
				offererId: 'ASAQ',
				rights: 'RightsType.editor',
				user: {
					canBookFreeOffers: false,
					dateCreated: '2018-11-23T15:30:59.777063Z',
					departementCode: '93',
					email: 'delphine.pruski@epinay-sur-seine.fr',
					firstName: 'Delphine',
					isAdmin: false,
					lastName: 'PRUSKI',
					phoneNumber: null,
					postalCode: '93800',
					publicName: 'Delphine P',
				},
				userId: 'AVVQ',
				validationToken: null,
			},
		],
		address: '1 RUE QUETIGNY',
		bic: null,
		city: 'EPINAY SUR SEINE',
		dateCreated: '2018-11-23T15:30:59.778387Z',
		dateModifiedAtLastProvider: '2018-11-23T15:30:59.778380Z',
		iban: null,
		id: 'ASAQ',
		idAtProviders: null,
		isActive: true,
		lastProviderId: null,
		modelName: 'Offerer',
		name: 'COMMUNE D EPINAY SUR SEINE',
		postalCode: '93800',
		siren: '219300316',
		thumbCount: 0,
		validationToken: 'l798DHxknodZ66YlV2xoGsOF2Do',
	},
]
